/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router';

// Import Routes

import { Route as rootRoute } from './../../page/__root';
import { Route as LoginSuccessIndexImport } from './../../page/login/success/index';
import { Route as LoginFailIndexImport } from './../../page/login/fail/index';
import { Route as mainUserIndexImport } from './../../page/(main)/user/index';
import { Route as mainLotusIndexImport } from './../../page/(main)/lotus/index';
import { Route as mainLotusCreateIndexImport } from './../../page/(main)/lotus/create/index';

// Create Virtual Routes

const mainRouteLazyImport = createFileRoute('/(main)')();
const IndexLazyImport = createFileRoute('/')();
const mainLotusLotusIdIndexLazyImport = createFileRoute('/(main)/lotus/$lotusId/')();

// Create/Update Routes

const mainRouteLazyRoute = mainRouteLazyImport
  .update({
    id: '/(main)',
    path: '/',
    getParentRoute: () => rootRoute
  } as any)
  .lazy(() => import('./../../page/(main)/route.lazy').then((d) => d.Route));

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute
} as any).lazy(() => import('./../../page/index.lazy').then((d) => d.Route));

const LoginSuccessIndexRoute = LoginSuccessIndexImport.update({
  id: '/login/success/',
  path: '/login/success/',
  getParentRoute: () => rootRoute
} as any);

const LoginFailIndexRoute = LoginFailIndexImport.update({
  id: '/login/fail/',
  path: '/login/fail/',
  getParentRoute: () => rootRoute
} as any);

const mainUserIndexRoute = mainUserIndexImport
  .update({
    id: '/user/',
    path: '/user/',
    getParentRoute: () => mainRouteLazyRoute
  } as any)
  .lazy(() => import('./../../page/(main)/user/index.lazy').then((d) => d.Route));

const mainLotusIndexRoute = mainLotusIndexImport
  .update({
    id: '/lotus/',
    path: '/lotus/',
    getParentRoute: () => mainRouteLazyRoute
  } as any)
  .lazy(() => import('./../../page/(main)/lotus/index.lazy').then((d) => d.Route));

const mainLotusLotusIdIndexLazyRoute = mainLotusLotusIdIndexLazyImport
  .update({
    id: '/lotus/$lotusId/',
    path: '/lotus/$lotusId/',
    getParentRoute: () => mainRouteLazyRoute
  } as any)
  .lazy(() => import('./../../page/(main)/lotus/$lotusId/index.lazy').then((d) => d.Route));

const mainLotusCreateIndexRoute = mainLotusCreateIndexImport
  .update({
    id: '/lotus/create/',
    path: '/lotus/create/',
    getParentRoute: () => mainRouteLazyRoute
  } as any)
  .lazy(() => import('./../../page/(main)/lotus/create/index.lazy').then((d) => d.Route));

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexLazyImport;
      parentRoute: typeof rootRoute;
    };
    '/(main)': {
      id: '/(main)';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof mainRouteLazyImport;
      parentRoute: typeof rootRoute;
    };
    '/(main)/lotus/': {
      id: '/(main)/lotus/';
      path: '/lotus';
      fullPath: '/lotus';
      preLoaderRoute: typeof mainLotusIndexImport;
      parentRoute: typeof mainRouteLazyImport;
    };
    '/(main)/user/': {
      id: '/(main)/user/';
      path: '/user';
      fullPath: '/user';
      preLoaderRoute: typeof mainUserIndexImport;
      parentRoute: typeof mainRouteLazyImport;
    };
    '/login/fail/': {
      id: '/login/fail/';
      path: '/login/fail';
      fullPath: '/login/fail';
      preLoaderRoute: typeof LoginFailIndexImport;
      parentRoute: typeof rootRoute;
    };
    '/login/success/': {
      id: '/login/success/';
      path: '/login/success';
      fullPath: '/login/success';
      preLoaderRoute: typeof LoginSuccessIndexImport;
      parentRoute: typeof rootRoute;
    };
    '/(main)/lotus/create/': {
      id: '/(main)/lotus/create/';
      path: '/lotus/create';
      fullPath: '/lotus/create';
      preLoaderRoute: typeof mainLotusCreateIndexImport;
      parentRoute: typeof mainRouteLazyImport;
    };
    '/(main)/lotus/$lotusId/': {
      id: '/(main)/lotus/$lotusId/';
      path: '/lotus/$lotusId';
      fullPath: '/lotus/$lotusId';
      preLoaderRoute: typeof mainLotusLotusIdIndexLazyImport;
      parentRoute: typeof mainRouteLazyImport;
    };
  }
}

// Create and export the route tree

interface mainRouteLazyRouteChildren {
  mainLotusIndexRoute: typeof mainLotusIndexRoute;
  mainUserIndexRoute: typeof mainUserIndexRoute;
  mainLotusCreateIndexRoute: typeof mainLotusCreateIndexRoute;
  mainLotusLotusIdIndexLazyRoute: typeof mainLotusLotusIdIndexLazyRoute;
}

const mainRouteLazyRouteChildren: mainRouteLazyRouteChildren = {
  mainLotusIndexRoute: mainLotusIndexRoute,
  mainUserIndexRoute: mainUserIndexRoute,
  mainLotusCreateIndexRoute: mainLotusCreateIndexRoute,
  mainLotusLotusIdIndexLazyRoute: mainLotusLotusIdIndexLazyRoute
};

const mainRouteLazyRouteWithChildren = mainRouteLazyRoute._addFileChildren(mainRouteLazyRouteChildren);

export interface FileRoutesByFullPath {
  '/': typeof mainRouteLazyRouteWithChildren;
  '/lotus': typeof mainLotusIndexRoute;
  '/user': typeof mainUserIndexRoute;
  '/login/fail': typeof LoginFailIndexRoute;
  '/login/success': typeof LoginSuccessIndexRoute;
  '/lotus/create': typeof mainLotusCreateIndexRoute;
  '/lotus/$lotusId': typeof mainLotusLotusIdIndexLazyRoute;
}

export interface FileRoutesByTo {
  '/': typeof mainRouteLazyRouteWithChildren;
  '/lotus': typeof mainLotusIndexRoute;
  '/user': typeof mainUserIndexRoute;
  '/login/fail': typeof LoginFailIndexRoute;
  '/login/success': typeof LoginSuccessIndexRoute;
  '/lotus/create': typeof mainLotusCreateIndexRoute;
  '/lotus/$lotusId': typeof mainLotusLotusIdIndexLazyRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexLazyRoute;
  '/(main)': typeof mainRouteLazyRouteWithChildren;
  '/(main)/lotus/': typeof mainLotusIndexRoute;
  '/(main)/user/': typeof mainUserIndexRoute;
  '/login/fail/': typeof LoginFailIndexRoute;
  '/login/success/': typeof LoginSuccessIndexRoute;
  '/(main)/lotus/create/': typeof mainLotusCreateIndexRoute;
  '/(main)/lotus/$lotusId/': typeof mainLotusLotusIdIndexLazyRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/lotus' | '/user' | '/login/fail' | '/login/success' | '/lotus/create' | '/lotus/$lotusId';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/lotus' | '/user' | '/login/fail' | '/login/success' | '/lotus/create' | '/lotus/$lotusId';
  id:
    | '__root__'
    | '/'
    | '/(main)'
    | '/(main)/lotus/'
    | '/(main)/user/'
    | '/login/fail/'
    | '/login/success/'
    | '/(main)/lotus/create/'
    | '/(main)/lotus/$lotusId/';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute;
  mainRouteLazyRoute: typeof mainRouteLazyRouteWithChildren;
  LoginFailIndexRoute: typeof LoginFailIndexRoute;
  LoginSuccessIndexRoute: typeof LoginSuccessIndexRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  mainRouteLazyRoute: mainRouteLazyRouteWithChildren,
  LoginFailIndexRoute: LoginFailIndexRoute,
  LoginSuccessIndexRoute: LoginSuccessIndexRoute
};

export const routeTree = rootRoute._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/(main)",
        "/login/fail/",
        "/login/success/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/(main)": {
      "filePath": "(main)/route.lazy.tsx",
      "children": [
        "/(main)/lotus/",
        "/(main)/user/",
        "/(main)/lotus/create/",
        "/(main)/lotus/$lotusId/"
      ]
    },
    "/(main)/lotus/": {
      "filePath": "(main)/lotus/index.tsx",
      "parent": "/(main)"
    },
    "/(main)/user/": {
      "filePath": "(main)/user/index.tsx",
      "parent": "/(main)"
    },
    "/login/fail/": {
      "filePath": "login/fail/index.tsx"
    },
    "/login/success/": {
      "filePath": "login/success/index.tsx"
    },
    "/(main)/lotus/create/": {
      "filePath": "(main)/lotus/create/index.tsx",
      "parent": "/(main)"
    },
    "/(main)/lotus/$lotusId/": {
      "filePath": "(main)/lotus/$lotusId/index.lazy.tsx",
      "parent": "/(main)"
    }
  }
}
ROUTE_MANIFEST_END */
